-- 1. BUAT TIPE ENUM KUSTOM
-- (Enum untuk Role Pengguna)
CREATE TYPE public.user_role AS ENUM (
    'ADMIN',
    'MAHASISWA'
);

-- (Enum untuk Status Mahasiswa)
CREATE TYPE public.mahasiswa_status AS ENUM (
    'NON_ELIGIBLE',
    'ELIGIBLE',
    'INTERN',
    'ALUMNI'
);

-- (Enum untuk Status Aplikasi Magang)
CREATE TYPE public.aplikasi_status AS ENUM (
    'PENDING',
    'REVIEWED',
    'ACCEPTED',
    'REJECTED'
);


-- 2. TABEL PROFIL PENGGUNA (ADMIN & MAHASISWA)
-- Tabel ini akan menyimpan data publik pengguna dan terhubung ke tabel 'auth.users' bawaan Supabase.
CREATE TABLE public.profiles (
    id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email text UNIQUE,
    full_name text,
    role public.user_role DEFAULT 'MAHASISWA'::public.user_role NOT NULL
);

-- Komentar: Memberi tahu Supabase bahwa tabel 'profiles' terhubung ke 'auth.users'
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update their own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);


-- 3. TABEL DETAIL MAHASISWA (Untuk data tambahan)
-- Terhubung ke tabel 'profiles' jika role-nya 'MAHASISWA'.
CREATE TABLE public.mahasiswa_details (
    id uuid NOT NULL PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
    prodi text,
    semester integer,
    no_hp text,
    portfolio_url text, -- (Ini portfolio utama di profil)
    status public.mahasiswa_status DEFAULT 'NON_ELIGIBLE'::public.mahasiswa_status NOT NULL,
    is_featured boolean DEFAULT false NOT NULL -- (Untuk 'Eligible/Intern Student' di homepage)
);

-- Komentar: Kebijakan keamanan untuk detail mahasiswa
ALTER TABLE public.mahasiswa_details ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Mahasiswa details viewable by everyone." ON public.mahasiswa_details FOR SELECT USING (true);
CREATE POLICY "Mahasiswa can insert their own details." ON public.mahasiswa_details FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Mahasiswa can update their own details." ON public.mahasiswa_details FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Admin can update any details." ON public.mahasiswa_details FOR UPDATE USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'ADMIN'::public.user_role));


-- 4. TABEL BERITA & ACARA
CREATE TABLE public.berita_acara (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    category text,
    event_date timestamp,
    content text,
    image_url text,
    created_at timestamptz DEFAULT now() NOT NULL
);

-- Komentar: Berita/Acara bisa dilihat publik, tapi hanya Admin yang bisa membuat/mengubah.
ALTER TABLE public.berita_acara ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Berita/Acara is viewable by everyone." ON public.berita_acara FOR SELECT USING (true);
CREATE POLICY "Admin can manage Berita/Acara." ON public.berita_acara FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'ADMIN'::public.user_role));


-- 5. TABEL LOWONGAN MAGANG
CREATE TABLE public.lowongan_magang (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name text NOT NULL,
    company_description text,
    company_logo_url text,
    job_description text,
    qualification text,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL
);

-- Komentar: Lowongan bisa dilihat publik, tapi hanya Admin yang bisa mengelola.
ALTER TABLE public.lowongan_magang ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Lowongan is viewable by everyone." ON public.lowongan_magang FOR SELECT USING (true);
CREATE POLICY "Admin can manage Lowongan." ON public.lowongan_magang FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'ADMIN'::public.user_role));


-- 6. TABEL APLIKASI MAGANG (Data Lamaran)
CREATE TABLE public.aplikasi_magang (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mahasiswa_id uuid NOT NULL REFERENCES public.profiles(id),
    lowongan_id bigint NOT NULL REFERENCES public.lowongan_magang(id),
    status public.aplikasi_status DEFAULT 'PENDING'::public.aplikasi_status NOT NULL,
    alasan_apply text NOT NULL,
    portfolio_submitted_url text NULL, -- (BARU: Portfolio yang di-submit saat melamar)
    applied_at timestamptz DEFAULT now() NOT NULL,
    
    -- (Memastikan 1 mahasiswa hanya bisa apply 1 kali ke lowongan yang sama)
    CONSTRAINT unique_application UNIQUE (mahasiswa_id, lowongan_id)
);

-- Komentar: Kebijakan keamanan data aplikasi
ALTER TABLE public.aplikasi_magang ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Mahasiswa can see their own applications." ON public.aplikasi_magang FOR SELECT USING (auth.uid() = mahasiswa_id);
CREATE POLICY "Mahasiswa can insert their own application." ON public.aplikasi_magang FOR INSERT WITH CHECK (auth.uid() = mahasiswa_id);
CREATE POLICY "Admin can see and manage all applications." ON public.aplikasi_magang FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'ADMIN'::public.user_role));


-- 7. FUNGSI TRIGGER (Otomatis membuat profil saat user baru mendaftar)
-- (Supabase Auth -> public.profiles)
CREATE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, role)
  VALUES (
    NEW.id, 
    NEW.email,
    NEW.raw_user_meta_data->>'full_name',
    (NEW.raw_user_meta_data->>'role')::public.user_role
  );
  
  -- Jika role-nya MAHASISWA, buat juga entri di 'mahasiswa_details'
  IF (NEW.raw_user_meta_data->>'role')::public.user_role = 'MAHASISWA' THEN
    INSERT INTO public.mahasiswa_details (id)
    VALUES (NEW.id);
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- (Menjalankan fungsi di atas setiap kali ada user baru di 'auth.users')
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

